included:
    - GameDex

excluded:
    - Pods

disabled_rules:
    - trailing_whitespace
    - force_cast

line_length: 200

function_parameter_count: 4

function_body_length: 50
type_body_length: 300
file_length: 400
identifier_name:
  min_length: 1
